apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metallb-config-operator
  template:
    metadata:
      labels:
        run: metallb-config-operator
    spec:
      serviceAccountName: metallb-config-operator
      containers:
      - image: vavere/metallb-config:0.1
        name: metallb-config-operator
        resources:
          requests:
            cpu: "10m"
            memory: "48Mi"
          limits:
            cpu: "100m"
            memory: "96Mi"
