apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metallb-config-operator
  template:
    metadata:
      labels:
        run: metallb-config-operator
    spec:
      serviceAccountName: metallb-config-operator
      containers:
      - image: vavere/metallb-config-operator:0.0.2
        name: metallb-config-operator
        resources:
          requests:
            cpu: "10m"
            memory: "48Mi"
          limits:
            cpu: "100m"
            memory: "96Mi"
        env:
          - name: CONFIG_NAME
            value: config
          - name: CONFIG_NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
